file_manager/urls.py
from django.urls import path
from . import views

app_name = 'file_manager'
urlpatterns = [
    path('', views.upload, name='upload'),
    path('result', views.result, name='result')
]

file_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('file/', include('file_manager.urls'))
]

file_manager/models.py
from django.db import models

# Create your models here.

file_manager/views.py
from django.shortcuts import render
from django.http import Http404

# Create your views here.


def upload(request):
    return render(request, 'file_manager/upload.html')


def result(request):
    if request.method == 'POST':
        upload_file = request.FILES['document']
        del upload_file
    raise Http404("Upload file are delete")

templates/file_manager/upload.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

</head>
<body>
    <h3>Upload file</h3>
    <form class="form" action="{% url 'file_manager:result' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input class="file" type="file" name="document">
        <label>Введіть час(мс)</label>
        <input class="timer" type="number"  min="1" max="100000">
        <input class="turn" type="button" value="Upload">
    </form>

    <script src="{% static "file_manager/jquery-1.10.2.js" %}"></script>
    <script src="{% static "file_manager/main.js" %}"></script>
</body>
</html>